**ARITHMETIC OPERATIONS**

In [4]:
import numpy as np
var1=np.array([1,2,3,4,5])
var2=np.array([6,7,8,9,8])
var_add= var1+var2
var_mul=var1*var2
var_div= var1/var2
var_mod= var1 % var2
print("addition of two matrix",var_add)
print("multiplication of two matrix",var_mul)
print("division of two matrix",var_div)
print("modulus of two matrix ", var_mod)


addition of two matrix [ 7  9 11 13 13]
multiplication of two matrix [ 6 14 24 36 40]
division of two matrix [0.16666667 0.28571429 0.375      0.44444444 0.625     ]
modulus of two matrix  [1 2 3 4 5]


**BY USING FUNCTIONS**

In [9]:
var1=np.array([1,2,3,4,5])
var2=np.array([6,7,8,9,8])
var_add1=np.add(var1,var2)
var_mul1=np.multiply(var1,var2)
var_div1= np.divide(var1,var2)
var_mod1= np.mod(var1,var2)
var_rec= np.reciprocal(var1)
var_power = np.power(var1,var2)
print("addition of two matrix",var_add1)
print("multiplication of two matrix",var_mul1)
print("division of two matrix",var_div1)
print("modulus of two matrix ", var_mod1)
print("reciprocal of var1 matrix",var_rec)
print("power of var1 matrix",var_power)

addition of two matrix [ 7  9 11 13 13]
multiplication of two matrix [ 6 14 24 36 40]
division of two matrix [0.16666667 0.28571429 0.375      0.44444444 0.625     ]
modulus of two matrix  [1 2 3 4 5]
reciprocal of var1 matrix [1 0 0 0 0]
power of var1 matrix [     1    128   6561 262144 390625]


**arithmetic operations on 2D matrix**

In [13]:
x=np.array([[[1,2,4,5,6],[2,4,6,7,8],[6,6,8,2,5]]])
y=np.array([[[1,2,4,5,6],[2,4,6,7,8],[6,6,8,2,5]]])
addition= np.add(x,y)
multiply=np.multiply(x,y)
print(addition)
print(multiply)

[[[ 2  4  8 10 12]
  [ 4  8 12 14 16]
  [12 12 16  4 10]]]
[[[ 1  4 16 25 36]
  [ 4 16 36 49 64]
  [36 36 64  4 25]]]
