shuffle() -> randomly shuffles the array

In [5]:
import numpy as np
ar= np.array([67,34,78,32,68,68,67,89,21,34,34,34])
np.random.shuffle(ar)
print(ar)

[34 32 67 67 68 21 34 78 68 89 34 34]


unique()-> sort the array in ascending order and remove all the repeated elements
parameters:=
1)return_counts->returns how many times the each elements occurs

In [9]:
a= np.array([67,34,78,32,68,68,67,89,21,34,34,34])
x= np.unique(a,return_index=True,return_counts=True) #sort the array in ascending order and remove all the repeated elements
print(x)

(array([21, 32, 34, 67, 68, 78, 89]), array([8, 3, 1, 0, 4, 2, 7]), array([1, 1, 4, 2, 2, 1, 1]))


resize()-> used to resize the array into other dimensions

In [17]:
p= np.array([67,34,78,32,68,68,67,89,21,34,34,34])
x=np.resize(p,(6,2)) #resized the 1d array into 2d array
print(x)
print("flatten in column major",x.flatten(order="C")) #resize the 2d array in column major order
print("fla",x.flatten(order="F"))#resize the 2d array in row major order
print(x.flatten(order="K"))
print("ravel : ",np.ravel(p,order="C")) #it also resize the array into 1d column major order just like flatten functions

[[67 34]
 [78 32]
 [68 68]
 [67 89]
 [21 34]
 [34 34]]
[67 34 78 32 68 68 67 89 21 34 34 34]
[67 78 68 67 21 34 34 32 68 89 34 34]
[67 34 78 32 68 68 67 89 21 34 34 34]
ravel :  [67 34 78 32 68 68 67 89 21 34 34 34]
