In [7]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
x= np.where(arr==2) #gives the index value of that variables
print(x)

(array([1]),)


sorting an 1d or 2d array

In [8]:
a=np.array([23,99,1,2,4,89,32,68,21,76,1,0])
print(np.sort(a)) #sorted the array in ascending order
b=([[1,2,3,4],[78,21,87,14]]) #sorting of a 2d matrix or array
print(np.sort(b))
c=(["a","z","h","j","x","r"]) #sorting a string
print(np.sort(c))

[ 0  1  1  2  4 21 23 32 68 76 89 99]
[[ 1  2  3  4]
 [14 21 78 87]]
['a' 'h' 'j' 'r' 'x' 'z']


filter array

In [6]:
x=np.array([1,2,3,4,5])
filters=[True,True,False,False,True]
new_array=x[filters] #it filter out the true part of the array and created a new memorage storage of the array
print(new_array)

[1 2 5]
