**DATA TYPES AND TYPECASTING**

In [2]:
import numpy as np
var1= np.array([1,3,5,7,8,9,9,3])
print(f"data type of var 1 {var1}",var1.dtype) 

data type of var 1 [1 3 5 7 8 9 9 3] int64


In [3]:
import numpy as np
var2= np.array([1.0,89.3,67.8])
print(f"data type of var 1 {var2}",var2.dtype) 

data type of var 1 [ 1.  89.3 67.8] float64


**converting data types:-**

In [6]:
x1=np.array([1,2,3,4,5],dtype=np.int8)
print(x1.dtype)
print(type(x1))

int8
<class 'numpy.ndarray'>


In [8]:
x2=np.array([1,2,3,4,5,6,7,8,9], dtype="f") #converting it into float data types
print(x2.dtype)



float32


In [10]:
x3=np.array([1,2,4,5,6,7,4,5,7])
new=np.float32(x3) #converting into float data type
new1=np.int_(new)#again converting into integer data type

print("data type of x3",x3.dtype)
print("data type of new",new.dtype)
print("data type of new1",new1.dtype)
print(x3)
print(new)
print(new1)


data type of x3 int64
data type of new float32
data type of new1 int64
[1 2 4 5 6 7 4 5 7]
[1. 2. 4. 5. 6. 7. 4. 5. 7.]
[1 2 4 5 6 7 4 5 7]
