In [8]:
import numpy as np
arr2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d[0,3])
print(arr2d)

4
[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr3d=np.array([[[1,2,4],[1,5,7]]])
print(arr3d.ndim)
print(arr3d)
print(arr3d[0,1,1])

3
[[[1 2 4]
  [1 5 7]]]
5
