**INSERTING FUNCTION**

inserting number in 1d array

In [24]:
import numpy as np
arr=([1,4,5,96,7,23,5,6,3,23,76])
x= np.insert(arr,(2,4),[100,200]) #insert 100 in index 2 and 200 in index 4 respectively
print(x)

[  1   4 100   5  96 200   7  23   5   6   3  23  76]


inserting number in 2d array

In [8]:
a=np.array([[1,2,3,4],[56,67,89,7]])
y=np.insert(a,2,[22,23,24,25],axis=0) #row wise
z=np.insert(a,2,[22,23],axis=1)#column wise
print(y)
print()
print(z)

[[ 1  2  3  4]
 [56 67 89  7]
 [22 23 24 25]]

[[ 1  2 22  3  4]
 [56 67 23 89  7]]


**DELETE FUNCTION**

In [12]:
v=([1,4,5,96,7,23,5,6,3,23,76])
dels=np.delete(v,4) #deleting value at 4th index
print(v)
print()
print(dels)

[1, 4, 5, 96, 7, 23, 5, 6, 3, 23, 76]

[ 1  4  5 96 23  5  6  3 23 76]


In [23]:
l=np.array([[1,2,3,4],[56,67,89,7]])
dels1=np.delete(l,(0,0),axis=0)
dels2=np.delete(l,(0,1),axis=1)
print(l)
print()
print(dels1)
print()
print(dels2)

[[ 1  2  3  4]
 [56 67 89  7]]

[[56 67 89  7]]

[[ 3  4]
 [89  7]]
