concatenate function

In [2]:
import numpy as np
x= np.array([[1,2,4],[1,76,8]])
y= np.array([[9,8,9],[65,54,77]])
arr_new= np.concatenate((x,y),axis=0)
arr_new1= np.concatenate((x,y),axis=1)

print(arr_new)
print()
print(arr_new1)

[[ 1  2  4]
 [ 1 76  8]
 [ 9  8  9]
 [65 54 77]]

[[ 1  2  4  9  8  9]
 [ 1 76  8 65 54 77]]


using stack function

In [4]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
i= np.stack((a1,a2),axis=0)
j=np.vstack((a1,a2)) #column
k=np.hstack((a1,a2)) #row
f= np.dstack((a1,a2)) #height
print(i)
print(j)
print(k)
print(f)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


split array

In [8]:
v= np.array([1,2,3,4,5,6])
po= np.array_split(v,10)
print(po)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]
