**slicing of a matrix**

slicing in 1d matrix or array

In [5]:
import numpy as np
arr= np.array([1,2,4,5,6,8,6,6,3,4,67,7]) 
print(arr[0:5])
print(arr[:])
print(arr[::2]) #stepsize=2

[1 2 4 5 6]
[ 1  2  4  5  6  8  6  6  3  4 67  7]
[ 1  4  6  6  3 67]


slicing in 2d array or matrix

In [6]:
arr2d=np.array([[1,2,3,4],[1,7,8,99]])
print(arr2d[1,1:5])

[ 1  7  8 99]
