**matrix of zeros**

In [3]:
import numpy as np
ar_zero= np.zeros(4)
ar_zero1=np.zeros((3,4)) #2d zero matrix
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**matrix of Ones**

In [6]:
ar_one=np.ones(4)#4 represent no. of columns and default it takes 1 no.of rows
ar_one1=np.ones((5,3))#5 represent no.of rows and 3 represent number of columns
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**CREATING AN EMPTY ARRAY**

In [8]:
arr_empty=np.empty(4)
print(arr_empty)

[1. 1. 1. 1.]


**RANGE OF ELEMENTS**

In [10]:
arr_range=np.arange(7)
print(arr_range)

[0 1 2 3 4 5 6]


**IDENTITY MATRIX**

In [14]:
arr_dia=np.eye(5)
arr_dia1=np.eye(3,6)
print(arr_dia)
print()
print(arr_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


**LINSPACE**

In [17]:
ar_linspace=np.linspace(0,20,num=70)
print(ar_linspace)

[ 0.          0.28985507  0.57971014  0.86956522  1.15942029  1.44927536
  1.73913043  2.02898551  2.31884058  2.60869565  2.89855072  3.1884058
  3.47826087  3.76811594  4.05797101  4.34782609  4.63768116  4.92753623
  5.2173913   5.50724638  5.79710145  6.08695652  6.37681159  6.66666667
  6.95652174  7.24637681  7.53623188  7.82608696  8.11594203  8.4057971
  8.69565217  8.98550725  9.27536232  9.56521739  9.85507246 10.14492754
 10.43478261 10.72463768 11.01449275 11.30434783 11.5942029  11.88405797
 12.17391304 12.46376812 12.75362319 13.04347826 13.33333333 13.62318841
 13.91304348 14.20289855 14.49275362 14.7826087  15.07246377 15.36231884
 15.65217391 15.94202899 16.23188406 16.52173913 16.8115942  17.10144928
 17.39130435 17.68115942 17.97101449 18.26086957 18.55072464 18.84057971
 19.13043478 19.42028986 19.71014493 20.        ]
