CREATING TYPES OF ARRAY

In [12]:
import numpy as np
y= np.array([1,2,3,5,56,6])
print(y)
print(type(y))

[ 1  2  3  5 56  6]
<class 'numpy.ndarray'>


In [3]:
lists=[]
for i in range(1,5):
    a=int(input("enter the number"))
    lists.append(a)
print(np.array(lists))
    

enter the number 56
enter the number 567
enter the number 23
enter the number 78


[ 56 567  23  78]


In [5]:
#creating 2 dimension array
ar2=np.array([[1,2,3,4,5],[2,56,7,9,3]])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4  5]
 [ 2 56  7  9  3]]
2


In [6]:
#creating 3d array
ar3= np.array([[[1,2,4,5,7,8],[3,5,78,8,67,8],[0,5,4,3,2,1]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  4  5  7  8]
  [ 3  5 78  8 67  8]
  [ 0  5  4  3  2  1]]]
3


In [8]:
#creating multi dimensional array
arn= np.array([1,2,3,4,5],ndmin=30)
print(arn)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
